package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	cli "spwn.sh/apps/cli"

	"github.com/spf13/cobra/doc"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "Usage: gen-docs <output-dir>")
		os.Exit(1)
	}
	outDir := os.Args[1]

	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	// Every page opens on the GENERATED marker the docs layout gate looks for
	// on the first line, then the frontmatter the Next.js pages read.
	prepend := func(filename string) string {
		name := filepath.Base(filename)
		name = strings.TrimSuffix(name, ".md")
		title := strings.ReplaceAll(name, "_", " ")
		slug := strings.ReplaceAll(name, "_", "-")
		return fmt.Sprintf(`<!-- GENERATED by "make docs" from the Cobra command tree. Do not edit. -->
---
title: "%s"
slug: "%s"
---

`, title, slug)
	}

	// Link handler for cross-references between commands.
	// Uses relative paths with .md extension so links render correctly
	// on GitHub's markdown file browser (absolute /docs/cli/spwn-agent
	// style breaks because GitHub needs the real filename).
	link := func(name string) string {
		return "./" + name
	}

	cmd := cli.GetRootCmd()
	cmd.DisableAutoGenTag = true

	if err := doc.GenMarkdownTreeCustom(cmd, outDir, prepend, link); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	fmt.Printf("Generated CLI docs in %s\n", outDir)
}
