.PHONY: build build-image build-test-image build-gate test test-universe test-agent test-gate test-e2e test-e2e-universe test-e2e-agent lint clean

build:
	cd cli && go build -o ../bin/spwn ./cmd/spwn

build-image:
	docker build -t spwn-base:latest ./domains/universe/internal/container

build-test-image:
	docker build -t spwn-test:latest -f container/Dockerfile.test ./__tests__/mock

build-gate:
	cd container/gate && cargo build --release

test:
	cd shared && go test ./...
	cd domains/agent && go test ./...
	cd domains/gate && go test ./...
	cd domains/universe && go test ./...
	cd cli && go test ./...

test-universe:
	cd domains/universe && go test ./...

test-agent:
	cd domains/agent && go test ./...

test-gate:
	cd domains/gate && go test ./...

test-e2e: test-e2e-universe test-e2e-agent

test-e2e-universe: build-test-image
	cd domains/universe && go test -v -tags=e2e -timeout=5m ./tests/e2e/...

test-e2e-agent:
	cd domains/agent && go test -v -tags=e2e -timeout=3m ./tests/e2e/...

lint:
	cd shared && go vet ./...
	cd domains/agent && go vet ./...
	cd domains/gate && go vet ./...
	cd domains/universe && go vet ./...
	cd cli && go vet ./...

clean:
	rm -rf bin/
	cd container/gate && cargo clean 2>/dev/null || true
