package codex

import (
	"encoding/json"
	"strings"
	"testing"

	"spwn.sh/packages/transpile"
)

// Renderer contract tests. See golden fixtures under
// packages/runtimes/testdata/*/output_codex/ for whole-tree
// diffing; these cases exercise individual invariants at the
// section level so a failing test points at a specific section
// rather than "goldens diverged".

func TestRenderer_Name(t *testing.T) {
	if got := Renderer.Name(); got != "codex" {
		t.Errorf("Name() = %q, want codex", got)
	}
}

func TestRender_EmitsAgentsMDAndRoleMD(t *testing.T) {
	tree, err := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo", Role: "worker"}},
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	paths := tree.Paths()
	wantPaths := map[string]bool{
		"agents/neo/AGENTS.md":          false,
		"agents/neo/.codex/config.toml": false, // always emitted so codex picks up spwn-owned flags
	}
	for _, p := range paths {
		if _, ok := wantPaths[p]; ok {
			wantPaths[p] = true
		}
	}
	for p, seen := range wantPaths {
		if !seen {
			t.Errorf("tree missing %s", p)
		}
	}
	// role.md used to be emitted alongside AGENTS.md; the role line
	// is inlined into AGENTS.md now so the side file must NOT exist.
	for _, p := range paths {
		if strings.Contains(p, "/worlds/") && strings.HasSuffix(p, "/role.md") {
			t.Errorf("tree still emits role.md at %s — role is inlined into AGENTS.md now", p)
		}
	}
}

// TestRender_SkillsLandInAgentsSkillsTree — codex follows the
// cross-vendor `.agents/skills/` convention (NOT `.codex/skills/`).
// All file types in a skill survive the emission.
func TestRender_SkillsLandInAgentsSkillsTree(t *testing.T) {
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo"}},
		Skills: []transpile.SkillEntry{
			{
				Name: "greeter",
				Files: map[string][]byte{
					"SKILL.md":         []byte("---\nname: greeter\ndescription: g\n---"),
					"references/x.md":  []byte("ref"),
					"scripts/run.sh":   []byte("#!/bin/bash\necho"),
				},
			},
		},
	})
	for _, p := range []string{
		"agents/neo/.agents/skills/greeter/SKILL.md",
		"agents/neo/.agents/skills/greeter/references/x.md",
		"agents/neo/.agents/skills/greeter/scripts/run.sh",
	} {
		if !tree.Has(p) {
			t.Errorf("tree missing %s — codex skills must live under .agents/skills/", p)
		}
	}
	// Guard against accidentally emitting codex-flavoured paths.
	for _, p := range tree.Paths() {
		if strings.HasPrefix(p, "agents/neo/.codex/skills/") {
			t.Errorf("codex skills must NOT live under .codex/skills/; got %s", p)
		}
	}
}

// TestRender_ConfigTOML_SkeletonAlwaysPresent — even with no model
// and no hooks, the config.toml is still emitted so codex always sees
// the spwn header + picks up any future knobs we add.
func TestRender_ConfigTOML_SkeletonAlwaysPresent(t *testing.T) {
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo"}},
	})
	body, ok := tree.Get("agents/neo/.codex/config.toml")
	if !ok {
		t.Fatal("missing config.toml")
	}
	if !strings.Contains(string(body), "Generated by spwn") {
		t.Error("config.toml missing spwn header comment")
	}
}

// TestRender_ConfigTOML_ModelPinsProfile — AgentInput.Model drives the
// `profile = "<agent>"` + `[profiles.<agent>] model = "..."` pair so
// codex auto-selects the model when invoked from the agent cwd.
func TestRender_ConfigTOML_ModelPinsProfile(t *testing.T) {
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo", Model: "gpt-5"}},
	})
	body, _ := tree.Get("agents/neo/.codex/config.toml")
	s := string(body)
	for _, want := range []string{
		`profile = "neo"`,
		`[profiles.neo]`,
		`model = "gpt-5"`,
	} {
		if !strings.Contains(s, want) {
			t.Errorf("config.toml missing %q; got:\n%s", want, s)
		}
	}
}

// TestRender_ConfigTOML_NoModelOmitsProfile — an unset model must not
// emit an empty profile pin that codex would interpret as an active
// profile with no model pinned.
func TestRender_ConfigTOML_NoModelOmitsProfile(t *testing.T) {
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo"}},
	})
	body, _ := tree.Get("agents/neo/.codex/config.toml")
	if strings.Contains(string(body), "profile") {
		t.Errorf("no model → no profile block; got:\n%s", body)
	}
}

// TestRender_HooksJSON_emittedWhenHooksExist — presence of any hook
// must produce both `.codex/hooks.json` AND the `codex_hooks = true`
// feature flag in `.codex/config.toml`. Without the flag, codex
// ignores the hooks file entirely.
func TestRender_HooksJSON_emittedWhenHooksExist(t *testing.T) {
	hooks := []transpile.HookEntry{
		{Name: "audit", Event: "PreToolUse", Matcher: "Bash", Command: "echo"},
	}
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo", Hooks: hooks}},
		Hooks:   hooks,
	})
	hooksJSON, ok := tree.Get("agents/neo/.codex/hooks.json")
	if !ok {
		t.Fatal("missing .codex/hooks.json")
	}
	if !strings.Contains(string(hooksJSON), "PreToolUse") {
		t.Errorf("hooks.json missing PreToolUse; got:\n%s", hooksJSON)
	}

	cfg, _ := tree.Get("agents/neo/.codex/config.toml")
	if !strings.Contains(string(cfg), "codex_hooks = true") {
		t.Errorf("config.toml missing codex_hooks feature flag; got:\n%s", cfg)
	}
}

// TestRender_HooksJSON_omittedWhenEmpty — no hooks in the input means
// no hooks.json file + no `codex_hooks` flag (dormant flags invite
// misleading config audits).
func TestRender_HooksJSON_omittedWhenEmpty(t *testing.T) {
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo"}},
	})
	if tree.Has("agents/neo/.codex/hooks.json") {
		t.Error("no hooks → hooks.json must not exist")
	}
	cfg, _ := tree.Get("agents/neo/.codex/config.toml")
	if strings.Contains(string(cfg), "codex_hooks") {
		t.Errorf("no hooks → no codex_hooks flag; got:\n%s", cfg)
	}
}

// TestRender_HooksJSON_shape — matches the cross-runtime envelope
// (same shape claude uses in settings.json#hooks) so a single spwn
// HookEntry fans into both targets without format drift.
func TestRender_HooksJSON_shape(t *testing.T) {
	hooks := []transpile.HookEntry{
		{Name: "a", Event: "PreToolUse", Matcher: "Bash", Command: "echo a"},
		{Name: "b", Event: "UserPromptSubmit", Command: "echo b"},
	}
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo", Hooks: hooks}},
		Hooks:   hooks,
	})
	body, _ := tree.Get("agents/neo/.codex/hooks.json")
	var parsed struct {
		Hooks map[string][]struct {
			Matcher string `json:"matcher"`
			Hooks   []struct {
				Type    string `json:"type"`
				Command string `json:"command"`
			} `json:"hooks"`
		} `json:"hooks"`
	}
	if err := json.Unmarshal(body, &parsed); err != nil {
		t.Fatalf("hooks.json bad JSON: %v", err)
	}
	if len(parsed.Hooks) != 2 {
		t.Fatalf("events: got %d, want 2", len(parsed.Hooks))
	}
	pre := parsed.Hooks["PreToolUse"][0]
	if pre.Matcher != "Bash" || pre.Hooks[0].Command != "echo a" {
		t.Errorf("PreToolUse shape: %+v", pre)
	}
	ups := parsed.Hooks["UserPromptSubmit"][0]
	if ups.Matcher != "*" {
		t.Errorf("UserPromptSubmit matcher: got %q, want \"*\" (empty must default)", ups.Matcher)
	}
}

// TestRender_RoleInlinedIntoAgentsMD — role flows into the AGENTS.md
// "## Role here" block as a single sentence. No separate role.md file.
func TestRender_RoleInlinedIntoAgentsMD(t *testing.T) {
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo", Role: "chief"}},
	})
	body, ok := tree.Get("agents/neo/AGENTS.md")
	if !ok {
		t.Fatal("missing AGENTS.md")
	}
	if !strings.Contains(string(body), "deployed as a chief in home") {
		t.Errorf("role not inlined into AGENTS.md; got:\n%s", body)
	}
}

// TestRender_EmptyRoleDefaultsToWorker — an unset role is still
// surfaced in the AGENTS.md, defaulting to "worker" so the agent
// always knows its stance in the world.
func TestRender_EmptyRoleDefaultsToWorker(t *testing.T) {
	tree, _ := Renderer.Render(transpile.Input{
		WorldID: "home",
		Agents:  []transpile.AgentInput{{Name: "neo"}},
	})
	body, _ := tree.Get("agents/neo/AGENTS.md")
	if !strings.Contains(string(body), "deployed as a worker in home") {
		t.Errorf("empty role should default to worker; got:\n%s", body)
	}
}

func TestGenerateAgentAgentsMD_IncludesAllSections(t *testing.T) {
	out := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo",
		Role:      "worker",
		WorldID:   "home",
		Soul:      []byte("# Neo\n\nYou are relentless."),
		Physics:   "# Physics of This World\n\n## Laws\n- Network: bridge\n",
		Faculties: "# Faculties\n\n## Tools\nspwn:unix\n",
		Roster:    "# Roster - home\n\nsome roster body\n",
		Playbooks: []transpile.PlaybookEntry{{Name: "deploy", Description: "Ship the change."}},
		AgentMD:   []byte("You help with CI audits."),
		KnowledgeMounted: true,
	})
	for _, want := range []string{
		"# neo — worker in world \"home\"",
		"## Identity",
		"You are relentless.",
		"## Physics",
		"Network: bridge",
		"## Faculties",
		"spwn:unix",
		"## Roster",
		"some roster body",
		"## Role here",
		"deployed as a worker in home",
		"## Your playbooks",
		"**deploy** — Ship the change.",
		"## Conventions",
		"World knowledge",
		"## Task",
		"You help with CI audits.",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q; got:\n%s", want, out)
		}
	}
}

func TestGenerateAgentAgentsMD_NoSoulSkipsIdentity(t *testing.T) {
	out := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo", Role: "worker", WorldID: "home",
		Physics: "# P\n", Faculties: "# F\n", Roster: "# R\n",
	})
	if strings.Contains(out, "## Identity") {
		t.Errorf("blank Soul should omit the Identity section; got:\n%s", out)
	}
}

func TestGenerateAgentAgentsMD_WhitespaceOnlySoulSkipsIdentity(t *testing.T) {
	out := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo", Role: "worker", WorldID: "home",
		Soul:    []byte("   \n\t\n"),
		Physics: "# P\n", Faculties: "# F\n", Roster: "# R\n",
	})
	if strings.Contains(out, "## Identity") {
		t.Errorf("whitespace-only Soul should omit Identity; got:\n%s", out)
	}
}

func TestGenerateAgentAgentsMD_EmptyPlaybooksSkipsSection(t *testing.T) {
	out := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo", Role: "worker", WorldID: "home",
		Physics: "# P\n", Faculties: "# F\n", Roster: "# R\n",
	})
	if strings.Contains(out, "## Your playbooks") {
		t.Errorf("empty Playbooks should omit the section; got:\n%s", out)
	}
}

func TestGenerateAgentAgentsMD_KnowledgeFlagTogglesConvention(t *testing.T) {
	with := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo", Role: "worker", WorldID: "home",
		Physics: "# P\n", Faculties: "# F\n", Roster: "# R\n",
		KnowledgeMounted: true,
	})
	without := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo", Role: "worker", WorldID: "home",
		Physics: "# P\n", Faculties: "# F\n", Roster: "# R\n",
	})
	if !strings.Contains(with, "World knowledge") {
		t.Error("KnowledgeMounted=true should emit the World knowledge bullet")
	}
	if strings.Contains(without, "World knowledge") {
		t.Error("KnowledgeMounted=false should NOT mention World knowledge")
	}
}

func TestGenerateAgentAgentsMD_NoAgentMDSkipsTask(t *testing.T) {
	out := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo", Role: "worker", WorldID: "home",
		Physics: "# P\n", Faculties: "# F\n", Roster: "# R\n",
	})
	if strings.Contains(out, "## Task") {
		t.Errorf("blank AgentMD should omit the Task section; got:\n%s", out)
	}
}

func TestGenerateAgentAgentsMD_HeadingsInInlinedBlocksAreDemoted(t *testing.T) {
	// A physics block has `## Laws` at H2. After inlining under the
	// wrapper's own `## Physics`, those inner H2s must demote to H3
	// so the outline reads cleanly.
	out := GenerateAgentAgentsMD(AgentAgentsMDInput{
		AgentName: "neo", Role: "worker", WorldID: "home",
		Physics:   "# Physics of This World\n\n## Laws\nrules\n",
		Faculties: "# F\n", Roster: "# R\n",
	})
	if !strings.Contains(out, "### Laws") {
		t.Errorf("inner ## Laws should demote to ### Laws; got:\n%s", out)
	}
	if strings.Contains(out, "# Physics of This World") {
		t.Errorf("the inner H1 should be stripped; got:\n%s", out)
	}
}

func TestRender_MultiAgentRosterSeenByEach(t *testing.T) {
	// Both agents should see the same roster; the worldbook helper
	// produces one roster body and every AGENTS.md inlines it.
	tree, err := Renderer.Render(transpile.Input{
		WorldID: "colony",
		Agents: []transpile.AgentInput{
			{Name: "alice", Role: "chief"},
			{Name: "bob", Role: "worker"},
		},
	})
	if err != nil {
		t.Fatalf("render: %v", err)
	}
	for _, name := range []string{"alice", "bob"} {
		body, ok := tree.Get("agents/" + name + "/AGENTS.md")
		if !ok {
			t.Fatalf("missing AGENTS.md for %s", name)
		}
		s := string(body)
		if !strings.Contains(s, "**alice** (chief)") || !strings.Contains(s, "**bob** (worker)") {
			t.Errorf("%s's AGENTS.md missing peer roster entries", name)
		}
	}
}
