package codex

import (
	"encoding/json"
	"strings"
	"testing"

	"spwn.sh/packages/transpile"
)

// Unit tests for the codex config/hooks generators. The renderer-level
// suite in render_test.go covers the happy paths through Render();
// these zoom in on the generator outputs so shape breaks point at the
// specific helper rather than the whole tree.

func TestGenerateAgentConfigTOML_skeletonOnly(t *testing.T) {
	body := string(GenerateAgentConfigTOML(ConfigInput{AgentName: "neo"}))
	if !strings.Contains(body, "Generated by spwn") {
		t.Error("missing spwn-ownership header comment")
	}
	for _, banned := range []string{"profile", "codex_hooks", "[profiles"} {
		if strings.Contains(body, banned) {
			t.Errorf("skeleton config contains %q; got:\n%s", banned, body)
		}
	}
}

func TestGenerateAgentConfigTOML_modelWithoutAgentNameOmitsProfile(t *testing.T) {
	// The generator anchors the profile key on AgentName; a bare Model
	// with no AgentName is a misuse we degrade to "skeleton only" rather
	// than emit a half-formed `[profiles.] model = ...` block.
	body := string(GenerateAgentConfigTOML(ConfigInput{Model: "gpt-5"}))
	if strings.Contains(body, "profile") {
		t.Errorf("profile block emitted without AgentName; got:\n%s", body)
	}
}

func TestGenerateAgentConfigTOML_modelAndAgentEmitProfile(t *testing.T) {
	body := string(GenerateAgentConfigTOML(ConfigInput{
		AgentName: "neo",
		Model:     "sonnet",
	}))
	for _, want := range []string{
		`profile = "neo"`,
		`[profiles.neo]`,
		`model = "sonnet"`,
	} {
		if !strings.Contains(body, want) {
			t.Errorf("missing %q; got:\n%s", want, body)
		}
	}
}

func TestGenerateAgentConfigTOML_hasHooksFlag(t *testing.T) {
	body := string(GenerateAgentConfigTOML(ConfigInput{AgentName: "neo", HasHooks: true}))
	if !strings.Contains(body, "[features]") || !strings.Contains(body, "codex_hooks = true") {
		t.Errorf("HasHooks=true should emit the feature block; got:\n%s", body)
	}
}

func TestGenerateAgentConfigTOML_noHooksOmitsFeatureFlag(t *testing.T) {
	body := string(GenerateAgentConfigTOML(ConfigInput{AgentName: "neo", HasHooks: false}))
	if strings.Contains(body, "codex_hooks") {
		t.Errorf("HasHooks=false should omit the feature flag; got:\n%s", body)
	}
}

func TestGenerateAgentHooksJSON_emptyReturnsNil(t *testing.T) {
	if got := GenerateAgentHooksJSON(nil); got != nil {
		t.Errorf("nil hooks: got %q, want nil", got)
	}
	if got := GenerateAgentHooksJSON([]transpile.HookEntry{}); got != nil {
		t.Errorf("empty hooks: got %q, want nil", got)
	}
}

func TestGenerateAgentHooksJSON_validJSON(t *testing.T) {
	body := GenerateAgentHooksJSON([]transpile.HookEntry{
		{Name: "x", Event: "PreToolUse", Matcher: "Bash", Command: "echo x"},
	})
	if !json.Valid(body) {
		t.Fatalf("output is not valid JSON:\n%s", body)
	}
	if len(body) == 0 || body[len(body)-1] != '\n' {
		t.Error("output must end with a trailing newline")
	}
}

// TestGenerateAgentHooksJSON_mirrorsClaudeSchema — the cross-runtime
// envelope {event: [{matcher, hooks:[{type:"command", command}]}]}
// is a deliberate design choice so one spwn HookEntry fans out to both
// targets. Schema drift here would break the parity.
func TestGenerateAgentHooksJSON_mirrorsClaudeSchema(t *testing.T) {
	body := GenerateAgentHooksJSON([]transpile.HookEntry{
		{Name: "x", Event: "PreToolUse", Matcher: "Bash", Command: "echo x"},
		{Name: "y", Event: "SessionStart", Command: "echo y"},
	})
	var parsed struct {
		Hooks map[string][]struct {
			Matcher string `json:"matcher"`
			Hooks   []struct {
				Type    string `json:"type"`
				Command string `json:"command"`
			} `json:"hooks"`
		} `json:"hooks"`
	}
	if err := json.Unmarshal(body, &parsed); err != nil {
		t.Fatalf("bad JSON: %v", err)
	}
	if len(parsed.Hooks) != 2 {
		t.Fatalf("event count: got %d, want 2", len(parsed.Hooks))
	}
	if parsed.Hooks["PreToolUse"][0].Matcher != "Bash" {
		t.Errorf("PreToolUse matcher = %q, want Bash", parsed.Hooks["PreToolUse"][0].Matcher)
	}
	if parsed.Hooks["SessionStart"][0].Matcher != "*" {
		t.Errorf("empty matcher must default to \"*\"; got %q", parsed.Hooks["SessionStart"][0].Matcher)
	}
	if parsed.Hooks["PreToolUse"][0].Hooks[0].Type != "command" {
		t.Errorf("hook type = %q, want command", parsed.Hooks["PreToolUse"][0].Hooks[0].Type)
	}
}

// TestGenerateAgentHooksJSON_groupsByEvent — multiple entries under
// the same event must collapse into one array (valid JSON), not
// duplicate keys.
func TestGenerateAgentHooksJSON_groupsByEvent(t *testing.T) {
	body := GenerateAgentHooksJSON([]transpile.HookEntry{
		{Name: "a", Event: "PreToolUse", Matcher: "Bash", Command: "a"},
		{Name: "b", Event: "PreToolUse", Matcher: "Edit", Command: "b"},
	})
	var parsed struct {
		Hooks map[string][]any `json:"hooks"`
	}
	if err := json.Unmarshal(body, &parsed); err != nil {
		t.Fatalf("bad JSON: %v", err)
	}
	if len(parsed.Hooks["PreToolUse"]) != 2 {
		t.Errorf("PreToolUse entries: got %d, want 2", len(parsed.Hooks["PreToolUse"]))
	}
}
