package codex

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"spwn.sh/packages/transpile"
)

// ConfigInput captures the per-agent knobs the renderer folds into
// `.codex/config.toml`. Growing this struct (instead of threading new
// parameters through every function) keeps the render API stable as
// codex primitives come online (profiles, model pins, project trust).
type ConfigInput struct {
	// AgentName is the profile key under `[profiles.<name>]`. Codex
	// matches the active profile by name, so it must equal the
	// agent's canonical name.
	AgentName string

	// Model mirrors agent.yaml#runtime.model. Written into
	// `[profiles.<agent>] model = "..."` when non-empty so the agent's
	// cwd-scoped codex invocation picks it up automatically.
	Model string

	// HasHooks toggles the `[features] codex_hooks = true` line. The
	// config.toml is emitted unconditionally (codex reads it even
	// when empty), but the feature flag is only written when hooks
	// actually exist — otherwise the file carries a dormant flag for
	// a capability the project doesn't use.
	HasHooks bool
}

// GenerateAgentConfigTOML emits the per-agent `.codex/config.toml`
// body. Codex auto-loads this file when the project is trusted; the
// spawn adapter's `PrelaunchShell` handles the trust-seed via the
// user-level `~/.codex/config.toml` at startup.
//
// V1 carries just the hooks feature flag. Future calls grow this with
// model / profile / MCP / approval-mode bindings as those primitives
// land in spwn's source format.
func GenerateAgentConfigTOML(in ConfigInput) []byte {
	var sb strings.Builder
	sb.WriteString("# Generated by spwn — do not edit by hand.\n")
	sb.WriteString("# Source: spwn/hooks.yaml + spwn/agents/<name>/agent.yaml\n\n")

	// The profile pin auto-selects this config's model whenever codex
	// is invoked from the agent's cwd. Profile name matches the
	// agent name so callers can still pass `--profile` explicitly.
	if in.Model != "" && in.AgentName != "" {
		sb.WriteString("profile = \"")
		sb.WriteString(in.AgentName)
		sb.WriteString("\"\n\n")
		sb.WriteString("[profiles.")
		sb.WriteString(in.AgentName)
		sb.WriteString("]\n")
		sb.WriteString("model = \"")
		sb.WriteString(in.Model)
		sb.WriteString("\"\n\n")
	}

	if in.HasHooks {
		sb.WriteString("[features]\n")
		sb.WriteString("codex_hooks = true\n")
	}
	return []byte(sb.String())
}

// GenerateAgentHooksJSON emits the per-agent `.codex/hooks.json` body.
// Shape matches Claude Code's hooks schema closely — codex adopted
// the same event/matcher layering intentionally, so the transpile
// layer's HookEntry maps 1:1 across runtimes.
//
// Returns nil when there are no hooks so callers can skip the file
// entirely rather than emit `{}` noise.
func GenerateAgentHooksJSON(hooks []transpile.HookEntry) []byte {
	if len(hooks) == 0 {
		return nil
	}
	byEvent := map[string][]transpile.HookEntry{}
	for _, h := range hooks {
		byEvent[h.Event] = append(byEvent[h.Event], h)
	}
	events := make([]string, 0, len(byEvent))
	for ev := range byEvent {
		events = append(events, ev)
	}
	sort.Strings(events)

	hooksMap := map[string]any{}
	for _, ev := range events {
		var rendered []any
		for _, h := range byEvent[ev] {
			matcher := h.Matcher
			if matcher == "" {
				matcher = "*"
			}
			rendered = append(rendered, map[string]any{
				"matcher": matcher,
				"hooks": []any{
					map[string]any{
						"type":    "command",
						"command": h.Command,
					},
				},
			})
		}
		hooksMap[ev] = rendered
	}

	payload := map[string]any{"hooks": hooksMap}
	out, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		// MarshalIndent on this shape never fails at runtime; the
		// fallback exists for future refactors that grow the payload.
		return []byte(fmt.Sprintf("{\"error\":%q}", err.Error()))
	}
	return append(out, '\n')
}
