package worldbook

import (
	"fmt"
	"strings"
)

// ColonyAgentSpec is the per-agent slice of the world roster that a
// renderer needs: the agent's name and declared role.
type ColonyAgentSpec struct {
	Name string
	Role string
}

// GenerateRoster produces the world's authoritative list of who is
// currently in this world. Inlined by the claude-code renderer into
// each agent's CLAUDE.md under a "## Roster" heading — how agents
// learn "who am I in here with?" and how to address messages.
//
// Each agent still reads their own identity from SOUL.md and their
// per-deployment role from worlds/<world-id>/role.md.
//
// knowledgeMounted controls whether the roster advertises the shared
// /world/knowledge/ directory. When false, the paragraph is omitted —
// the agent is never told a knowledge base exists.
func GenerateRoster(worldID string, agents []ColonyAgentSpec, knowledgeMounted bool) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Roster - %s\n\n", worldID))
	if len(agents) == 0 {
		b.WriteString("This world has no agents currently deployed.\n")
		return b.String()
	}
	b.WriteString("The agents currently deployed in this world. Regenerated by spwn whenever the roster changes.\n\n")

	b.WriteString("## Members\n")
	for _, a := range agents {
		role := a.Role
		if role == "" {
			role = "worker"
		}
		b.WriteString(fmt.Sprintf("- **%s** (%s)\n", a.Name, role))
	}
	b.WriteString("\n")

	b.WriteString("## Where to find each member\n")
	b.WriteString("- Soul: `/agents/<name>/SOUL.md`\n")
	b.WriteString("- Playbooks: `/agents/<name>/playbooks/`\n")
	b.WriteString("- Journal: `/agents/<name>/journal/`\n")
	b.WriteString("- Inbox (this world): `/world/inbox/<name>/`\n")
	b.WriteString("\n")
	if knowledgeMounted {
		b.WriteString("Shared world knowledge (facts about the domain, not about any one agent) lives at `/world/knowledge/` — read and write freely; it's committed to the project.\n")
		b.WriteString("\n")
	}

	return b.String()
}
